In [5]:
import numpy as np
np.random.seed(5)
val = np.random.randint(10,50,size=(3,5))
print(val)
val[1:3,2:5]

[[45 24 48 26 19]
 [18 46 49 37 40]
 [26 17 22 25 49]]


array([[49, 37, 40],
       [22, 25, 49]])

In [4]:
import numpy as np
np.random.seed(5)
arr = np.random.randint(0,100,size=(9,9))
print(arr)




[[99 78 61 16 73  8 62 27 30]
 [80  7 76 15 53 80 27 44 77]
 [75 65 47 30 84 86 18  9 41]
 [62  1 82 16 78  5 58  0 80]
 [ 4 36 51 27 31  2 68 38 83]
 [19 18  7 30 62 11 67 65 55]
 [ 3 91 78 27 29 33 89 85  7]
 [16 94 14 90 31  9 38 47 16]
 [ 5 34 45 59 24 13 31 32 76]]


In [7]:
b=[]
for i in range(0,9):
  a = arr[i,:]
  print(a)
  b.append(a.mean())
  print(b)

In [ ]:
for i in range(0,9):
  c = arr[i,:]
  if(b[0]<c[i]):
    c[i]=0